import 'package:flutter/material.dart';
import '../services/storage_service.dart';

class AppLocalization {
  static final ValueNotifier<String> languageNotifier = ValueNotifier('English');

  static final Map<String, Map<String, String>> _localizedValues = {
    'English': {
      'Collection': 'Collection',
      'Expense': 'Expense',
      'Customer': 'Customer',
      'Reports': 'Reports',
      'Settings': 'Settings',
      'Support': 'Support',
      'License': 'License',
      'Line': 'Line',
      'Import Line': 'Import Line',
      'Export Line': 'Export Line',
      'Area': 'Area',
      'Expense Type': 'Expense Type',
      'Investment Type': 'Investment Type',
      'Site': 'Site',
      'My Settings': 'My Settings',
      'Language': 'Language',
      'Language Settings': 'Language Settings',
      'SMS Template': 'SMS Template',
      'Enable Fingerprint': 'Enable Fingerprint',
      'Enable Security Alert': 'Enable Security Alert',
      'Change Password': 'Change Password',
      'Theme Settings': 'Theme Settings',
      'Sign out': 'Sign out',
      'Exit App': 'Exit App',
      'Are you sure you want to exit the application?': 'Are you sure you want to exit the application?',
      'CANCEL': 'CANCEL',
      'EXIT': 'EXIT',
      'Customers': 'Customers',
      'Customer Profile': 'Customer Profile',
      'Add Customer': 'Add Customer',
      'Assign Loan': 'Assign Loan',
      'Active': 'Active',
      'Completed': 'Completed',
      'Principal': 'Principal',
      'Interest': 'Interest',
      'Daily Due': 'Daily Due',
      'Paid': 'Paid',
      'Balance': 'Balance',
      'Progress': 'Progress',
      'Save Record': 'Save Record',
      'Amount Collected': 'Amount Collected',
      'Notes (Optional)': 'Notes (Optional)',
      'Add Collection': 'Add Collection',
      'Date': 'Date',
      'SUBMIT': 'SUBMIT',
      'Select Theme': 'Select Theme',
      'Select Language': 'Select Language',
      'EXPENSE': 'EXPENSE',
      'INVESTMENT': 'INVESTMENT',
      'Select Line': 'Select Line',
      'Select Area': 'Select Area',
      'CLEAR': 'CLEAR',
      'Plan': 'Plan',
      'Daily Summary': 'Daily Summary',
      'Line Summary': 'Line Summary',
      'Online Collection Summary': 'Online Collection Summary',
      'Site Dashboard Summary': 'Site Dashboard Summary',
      'Expense Summary': 'Expense Summary',
      'Investment Summary': 'Investment Summary',
      'Investment/Expense Summary': 'Investment/Expense Summary',
      'Book Excess Loss Summary': 'Book Excess Loss Summary',
      'Loan Summary': 'Loan Summary',
      'About to Close Loan Summary': 'About to Close Loan Summary',
      'Missing Customer Summary': 'Missing Customer Summary',
      'Monthly Interest Pending Summary': 'Monthly Interest Pending Summary',
      'Completed Loan Summary': 'Completed Loan Summary',
      'Non Performance Loan Summary': 'Non Performance Loan Summary',
      'New Customer Summary': 'New Customer Summary',
      'Bad Loan Summary': 'Bad Loan Summary',
      'New Bad Loan By Date Summary': 'New Bad Loan By Date Summary',
      'Loan Analysis': 'Loan Analysis',
      'Ledger Report': 'Ledger Report',
      'Select filters and tap SUBMIT to load sheet.': 'Select filters and tap SUBMIT to load sheet.',
      'No customers found for this line/area.': 'No customers found for this line/area.',
      'Pending': 'Pending',
      'Pay': 'Pay',
      'Add Collection for': 'Add Collection for',
      'Select Loan for Payment': 'Select Loan for Payment',
      'SAVE RECORD': 'SAVE RECORD',
      'Add Investment': 'Add Investment',
      'Amount': 'Amount',
      'Category': 'Category',
      'Description (Optional)': 'Description (Optional)',
      'Payment Mode': 'Payment Mode',
      'Cash': 'Cash',
      'SAVE': 'SAVE',
      'Add Expense': 'Add Expense',
      'Please enter a valid amount': 'Please enter a valid amount',
      'Online': 'Online',
      'Send Receipt': 'Send Receipt',
      'Send collection receipt to': 'Send collection receipt to',
      'Customer Mobile Number': 'Customer Mobile Number',
      'Enter 10-digit number': 'Enter 10-digit number',
      'WHATSAPP': 'WHATSAPP',
      'SMS': 'SMS',
      'Skipped': 'Skipped',
      'No active loans found for this customer.': 'No active loans found for this customer.',
      'Customer Name': 'Customer Name',
      'Mobile Number': 'Mobile Number',
      'Address': 'Address',
      'Customer added successfully!': 'Customer added successfully!',
      'Assign Loan to': 'Assign Loan to',
      'Loan assigned successfully!': 'Loan assigned successfully!',
      'Principal Amount (₹)': 'Principal Amount (₹)',
      'Interest Amount (₹)': 'Interest Amount (₹)',
      'Duration (Days)': 'Duration (Days)',
      'Total Amount:': 'Total Amount:',
      'Daily Due Amount:': 'Daily Due Amount:',
      'ASSIGN LOAN': 'ASSIGN LOAN',
      'Required': 'Required',
      'Search': 'Search',
      'Search By Date': 'Search By Date',
      'From Date': 'From Date',
      'To Date': 'To Date',
      'Total': 'Total',
      'All': 'All',
      'Summary': 'Summary',
      'Search...': 'Search...',
      'No data found.': 'No data found.',
      'Edit Filters': 'Edit Filters',
      'Select filters and tap SUBMIT.': 'Select filters and tap SUBMIT.',
    },
    'தமிழ்': {
      'Collection': 'வசூல்',
      'Expense': 'செலவு',
      'Customer': 'வாடிக்கையாளர்',
      'Reports': 'அறிக்கைகள்',
      'Settings': 'அமைப்புகள்',
      'Support': 'உதவி',
      'License': 'உரிமம்',
      'Line': 'லைன்',
      'Import Line': 'இறக்குமதி செய்',
      'Export Line': 'ஏற்றுமதி செய்',
      'Area': 'பகுதி',
      'Expense Type': 'செலவு வகை',
      'Investment Type': 'முதலீடு வகை',
      'Site': 'தளம்',
      'My Settings': 'எனது அமைப்புகள்',
      'Language': 'மொழி',
      'Language Settings': 'மொழி அமைப்புகள்',
      'SMS Template': 'எஸ்எம்எஸ் டெம்ப்ளேட்',
      'Enable Fingerprint': 'கைரேகையை இயக்கு',
      'Enable Security Alert': 'பாதுகாப்பு எச்சரிக்கை',
      'Change Password': 'கடவுச்சொல்லை மாற்று',
      'Theme Settings': 'தீம் அமைப்புகள்',
      'Sign out': 'வெளியேறு',
      'Exit App': 'செயலியை மூடு',
      'Are you sure you want to exit the application?': 'செயலியை விட்டு வெளியேற விரும்புகிறீர்களா?',
      'CANCEL': 'ரத்துசெய்',
      'EXIT': 'வெளியேறு',
      'Customers': 'வாடிக்கையாளர்கள்',
      'Customer Profile': 'வாடிக்கையாளர் சுயவிவரம்',
      'Add Customer': 'வாடிக்கையாளர் சேர்',
      'Assign Loan': 'கடன் வழங்கு',
      'Active': 'செயலில் உள்ள',
      'Completed': 'முடிந்தது',
      'Principal': 'அசல்',
      'Interest': 'வட்டி',
      'Daily Due': 'தினசரி தவணை',
      'Paid': 'செலுத்தப்பட்டது',
      'Balance': 'மீதி பாக்கி',
      'Progress': 'முன்னேற்றம்',
      'Save Record': 'சேமி',
      'Amount Collected': 'வசூலித்த தொகை',
      'Notes (Optional)': 'குறிப்புகள் (விருப்பம்)',
      'Add Collection': 'வசூல் சேர்',
      'Date': 'தேதி',
      'SUBMIT': 'சமர்ப்பி',
      'Select Theme': 'தீம் தேர்ந்தெடுக்கவும்',
      'Select Language': 'மொழியைத் தேர்ந்தெடுக்கவும்',
      'EXPENSE': 'செலவு',
      'INVESTMENT': 'முதலீடு',
      'Select Line': 'லைனை தேர்ந்தெடு',
      'Select Area': 'பகுதியை தேர்ந்தெடு',
      'CLEAR': 'அழி',
      'Plan': 'தவணை திட்டம்',
      'Daily Summary': 'தினசரி அறிக்கை',
      'Line Summary': 'லைன் அறிக்கை',
      'Online Collection Summary': 'ஆன்லைன் வசூல் அறிக்கை',
      'Site Dashboard Summary': 'தள முகப்பு அறிக்கை',
      'Expense Summary': 'செலவு அறிக்கை',
      'Investment Summary': 'முதலீடு அறிக்கை',
      'Investment/Expense Summary': 'முதலீடு/செலவு அறிக்கை',
      'Book Excess Loss Summary': 'நஷ்ட கணக்கு அறிக்கை',
      'Loan Summary': 'கடன் அறிக்கை',
      'About to Close Loan Summary': 'முடியப்போகும் கடன் அறிக்கை',
      'Missing Customer Summary': 'தவறிய வாடிக்கையாளர் அறிக்கை',
      'Monthly Interest Pending Summary': 'மாதாந்திர வட்டி பாக்கி',
      'Completed Loan Summary': 'முடிவடைந்த கடன் அறிக்கை',
      'Non Performance Loan Summary': 'செயலற்ற கடன் அறிக்கை',
      'New Customer Summary': 'புதிய வாடிக்கையாளர் அறிக்கை',
      'Bad Loan Summary': 'வராக்கடன் அறிக்கை',
      'New Bad Loan By Date Summary': 'தேதி வாரி வராக்கடன் அறிக்கை',
      'Loan Analysis': 'கடன் பகுப்பாய்வு',
      'Ledger Report': 'பேரேடு அறிக்கை',
      'Select filters and tap SUBMIT to load sheet.': 'வடிகட்டிகளைத் தேர்ந்தெடுத்து சமர்ப்பி பொத்தானை அழுத்தவும்.',
      'No customers found for this line/area.': 'இந்த லைன்/பகுதியில் வாடிக்கையாளர்கள் இல்லை.',
      'Pending': 'பாக்கி',
      'Pay': 'வரவு வை',
      'Add Collection for': 'வசூல் சேர்',
      'Select Loan for Payment': 'கடன் கணக்கைத் தேர்ந்தெடுக்கவும்',
      'SAVE RECORD': 'சேமி',
      'Add Investment': 'முதலீடு சேர்',
      'Amount': 'தொகை',
      'Category': 'வகை',
      'Description (Optional)': 'விவரம் (விருப்பம்)',
      'Payment Mode': 'பண வகை',
      'Cash': 'பணம்',
      'SAVE': 'சேமி',
      'Add Expense': 'செலவு சேர்',
      'Please enter a valid amount': 'சரியான தொகையை உள்ளிடவும்',
      'Online': 'ஆன்லைன்',
      'Send Receipt': 'ரசீது அனுப்பு',
      'Send collection receipt to': 'வசூல் ரசீதை இவருக்கு அனுப்பவா:',
      'Customer Mobile Number': 'வாடிக்கையாளர் அலைபேசி எண்',
      'Enter 10-digit number': '10 இலக்க எண்ணை உள்ளிடவும்',
      'WHATSAPP': 'வாட்ஸ்அப்',
      'SMS': 'எஸ்எம்எஸ்',
      'Skipped': 'தவிர்க்கப்பட்டது',
      'No active loans found for this customer.': 'இந்த வாடிக்கையாளருக்கு செயலில் உள்ள கடன்கள் இல்லை.',
      'Customer Name': 'வாடிக்கையாளர் பெயர்',
      'Mobile Number': 'அலைபேசி எண்',
      'Address': 'முகவரி',
      'Customer added successfully!': 'வாடிக்கையாளர் வெற்றிகரமாக சேர்க்கப்பட்டார்!',
      'Assign Loan to': 'கடன் வழங்கு:',
      'Loan assigned successfully!': 'கடன் வெற்றிகரமாக வழங்கப்பட்டது!',
      'Principal Amount (₹)': 'அசல் தொகை (₹)',
      'Interest Amount (₹)': 'வட்டி தொகை (₹)',
      'Duration (Days)': 'கால அளவு (நாட்கள்)',
      'Total Amount:': 'மொத்த தொகை:',
      'Daily Due Amount:': 'தினசரி தவணை தொகை:',
      'ASSIGN LOAN': 'கடன் வழங்கு',
      'Required': 'தேவை',
      'Search': 'தேடு',
      'Search By Date': 'தேதி வாரி தேடல்',
      'From Date': 'தொடக்க தேதி',
      'To Date': 'முடிவு தேதி',
      'Total': 'மொத்தம்',
      'All': 'அனைத்தும்',
      'Summary': 'சுருக்கம்',
      'Search...': 'தேடு...',
      'No data found.': 'தரவு எதுவும் இல்லை.',
      'Edit Filters': 'வடிகட்டிகளை மாற்று',
      'Select filters and tap SUBMIT.': 'வடிகட்டிகளைத் தேர்ந்தெடுத்து சமர்ப்பிக்கவும்.',
    },
    'हिंदी': {
      'Collection': 'संग्रह',
      'Expense': 'व्यय',
      'Customer': 'ग्राहक',
      'Reports': 'रिपोर्ट',
      'Settings': 'सेटिंग्स',
      'Support': 'सहायता',
      'License': 'लाइसेंस',
      'Line': 'लाइन',
      'Import Line': 'लाइन आयात करें',
      'Export Line': 'लाइन निर्यात करें',
      'Area': 'क्षेत्र',
      'Expense Type': 'व्यय प्रकार',
      'Investment Type': 'निवेश प्रकार',
      'Site': 'साइट',
      'My Settings': 'मेरी सेटिंग्स',
      'Language': 'भाषा',
      'Language Settings': 'भाषा सेटिंग्स',
      'SMS Template': 'एसएमएस टेम्पलेट',
      'Enable Fingerprint': 'फिंगरप्रिंट सक्षम करें',
      'Enable Security Alert': 'सुरक्षा चेतावनी',
      'Change Password': 'पासवर्ड बदलें',
      'Theme Settings': 'थीम सेटिंग्स',
      'Sign out': 'साइन आउट',
      'Exit App': 'ऐप बंद करें',
      'Are you sure you want to exit the application?': 'क्या आप वाकई ऐप से बाहर निकलना चाहते हैं?',
      'CANCEL': 'रद्द करें',
      'EXIT': 'बाहर निकलें',
      'Customers': 'ग्राहक',
      'Customer Profile': 'ग्राहक प्रोफ़ाइल',
      'Add Customer': 'ग्राहक जोड़ें',
      'Assign Loan': 'ऋण सौंपें',
      'Active': 'सक्रिय',
      'Completed': 'पूरा हुआ',
      'Principal': 'मूलधन',
      'Interest': 'ब्याज',
      'Daily Due': 'दैनिक देय',
      'Paid': 'भुगतान किया',
      'Balance': 'शेष राशि',
      'Progress': 'प्रगति',
      'Save Record': 'रिकॉर्ड सहेजें',
      'Amount Collected': 'एकत्रित राशि',
      'Notes (Optional)': 'टिप्पणियाँ (वैकल्पिक)',
      'Add Collection': 'संग्रह जोड़ें',
      'Date': 'तारीख',
      'SUBMIT': 'जमा करें',
      'Select Theme': 'थीम चुनें',
      'Select Language': 'भाषा चुनें',
      'EXPENSE': 'व्यय',
      'INVESTMENT': 'निवेश',
      'Select Line': 'लाइन चुनें',
      'Select Area': 'क्षेत्र चुनें',
      'CLEAR': 'साफ़ करें',
      'Plan': 'योजना',
      'Daily Summary': 'दैनिक सारांश',
      'Line Summary': 'लाइन सारांश',
      'Online Collection Summary': 'ऑनलाइन संग्रह सारांश',
      'Site Dashboard Summary': 'साइट डैशबोर्ड सारांश',
      'Expense Summary': 'व्यय सारांश',
      'Investment Summary': 'निवेश सारांश',
      'Investment/Expense Summary': 'निवेश/व्यय सारांश',
      'Book Excess Loss Summary': 'पुस्तक अतिरिक्त हानि सारांश',
      'Loan Summary': 'ऋण सारांश',
      'About to Close Loan Summary': 'बंद होने वाले ऋण का सारांश',
      'Missing Customer Summary': 'लापता ग्राहक सारांश',
      'Monthly Interest Pending Summary': 'मासिक ब्याज लंबित सारांश',
      'Completed Loan Summary': 'पूरा हुआ ऋण सारांश',
      'Non Performance Loan Summary': 'गैर-निष्पादित ऋण सारांश',
      'New Customer Summary': 'नए ग्राहक सारांश',
      'Bad Loan Summary': 'खराब ऋण सारांश',
      'New Bad Loan By Date Summary': 'तारीख के अनुसार नया खराब ऋण सारांश',
      'Loan Analysis': 'ऋण विश्लेषण',
      'Ledger Report': 'लेजर रिपोर्ट',
      'Select filters and tap SUBMIT to load sheet.': 'फिल्टर चुनें और शीट लोड करने के लिए जमा करें पर टैप करें।',
      'No customers found for this line/area.': 'इस लाइन/क्षेत्र के लिए कोई ग्राहक नहीं मिला।',
      'Pending': 'लंबित',
      'Pay': 'भुगतान करें',
      'Add Collection for': 'संग्रह जोड़ें',
      'Select Loan for Payment': 'भुगतान के लिए ऋण चुनें',
      'SAVE RECORD': 'सहेजें',
      'Add Investment': 'निवेश जोड़ें',
      'Amount': 'मात्रा',
      'Category': 'श्रेणी',
      'Description (Optional)': 'विवरण (वैकल्पिक)',
      'Payment Mode': 'भुगतान का प्रकार',
      'Cash': 'नकद',
      'SAVE': 'सहेजें',
      'Add Expense': 'व्यय जोड़ें',
      'Please enter a valid amount': 'कृपया एक मान्य राशि दर्ज करें',
      'Online': 'ऑनलाइन',
      'Send Receipt': 'रसीद भेजें',
      'Send collection receipt to': 'संग्रह रसीद भेजें:',
      'Customer Mobile Number': 'ग्राहक मोबाइल नंबर',
      'Enter 10-digit number': '10 अंकों का नंबर दर्ज करें',
      'WHATSAPP': 'व्हाट्सएप',
      'SMS': 'एसएमएस',
      'Skipped': 'छोड़ा गया',
      'No active loans found for this customer.': 'इस ग्राहक के लिए कोई सक्रिय ऋण नहीं मिला।',
      'Customer Name': 'ग्राहक का नाम',
      'Mobile Number': 'मोबाइल नंबर',
      'Address': 'पता',
      'Customer added successfully!': 'ग्राहक सफलतापूर्वक जोड़ा गया!',
      'Assign Loan to': 'ऋण सौंपें:',
      'Loan assigned successfully!': 'ऋण सफलतापूर्वक सौंपा गया!',
      'Principal Amount (₹)': 'मूलधन राशि (₹)',
      'Interest Amount (₹)': 'ब्याज राशि (₹)',
      'Duration (Days)': 'अवधि (दिन)',
      'Total Amount:': 'कुल राशि:',
      'Daily Due Amount:': 'दैनिक देय राशि:',
      'ASSIGN LOAN': 'ऋण सौंपें',
      'Required': 'आवश्यक',
      'Search': 'खोजें',
      'Search By Date': 'तारीख से खोजें',
      'From Date': 'प्रारंभ तिथि',
      'To Date': 'अंतिम तिथि',
      'Total': 'कुल',
      'All': 'सभी',
      'Summary': 'सारांश',
      'Search...': 'खोजें...',
      'No data found.': 'कोई डेटा नहीं मिला।',
      'Edit Filters': 'फ़िल्टर बदलें',
      'Select filters and tap SUBMIT.': 'फ़िल्टर चुनें और सबमिट करें।',
    }
  };

  static void init(StorageService storageService) {
    final savedLang = storageService.getString('app_language', defaultValue: 'English');
    languageNotifier.value = savedLang;
  }

  static String translate(String key) {
    final currentLang = languageNotifier.value;
    return _localizedValues[currentLang]?[key] ?? key;
  }
}

extension TranslateString on String {
  String tr() {
    return AppLocalization.translate(this);
  }
}
