import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:go_router/go_router.dart';
import 'package:vasooldrive/core/services/app_localization.dart';

import '../../../../core/di/injection_container.dart';
import '../../../customers/domain/entities/customer_entity.dart';
import '../../domain/entities/loan_entity.dart';
import '../bloc/loans_bloc.dart';
import '../bloc/loans_event.dart';
import '../bloc/loans_state.dart';

class AddLoanPage extends StatelessWidget {
  final CustomerEntity customer;
  final LoanEntity? loan;

  const AddLoanPage({super.key, required this.customer, this.loan});

  @override
  Widget build(BuildContext context) {
    return BlocProvider(
      create: (_) => sl<LoansBloc>(),
      child: _AddLoanForm(customer: customer, loan: loan),
    );
  }
}

class _AddLoanForm extends StatefulWidget {
  final CustomerEntity customer;
  final LoanEntity? loan;

  const _AddLoanForm({required this.customer, this.loan});

  @override
  State<_AddLoanForm> createState() => _AddLoanFormState();
}

class _AddLoanFormState extends State<_AddLoanForm> {
  final _formKey = GlobalKey<FormState>();

  final _principalController = TextEditingController();
  final _interestController = TextEditingController();
  final _daysController = TextEditingController(text: '100');
  final _outstandingBalanceController = TextEditingController();

  double _totalAmount = 0.0;
  double _dailyDueAmount = 0.0;

  @override
  void initState() {
    super.initState();
    if (widget.loan != null) {
      _principalController.text = widget.loan!.principalAmount.toString();
      _interestController.text = widget.loan!.interestAmount.toString();
      final days = widget.loan!.endDate.difference(widget.loan!.startDate).inDays;
      _daysController.text = (days > 0 ? days : 100).toString();
      _totalAmount = widget.loan!.totalAmount;
      _dailyDueAmount = widget.loan!.dailyDueAmount;
      _outstandingBalanceController.text = widget.loan!.outstandingBalance.toString();
    }
    _principalController.addListener(_calculateMath);
    _interestController.addListener(_calculateMath);
    _daysController.addListener(_calculateMath);
  }

  @override
  void dispose() {
    _principalController.dispose();
    _interestController.dispose();
    _daysController.dispose();
    _outstandingBalanceController.dispose();
    super.dispose();
  }

  void _calculateMath() {
    final principal = double.tryParse(_principalController.text) ?? 0.0;
    final interest = double.tryParse(_interestController.text) ?? 0.0;
    final days = double.tryParse(_daysController.text) ?? 1.0; // Avoid divide by 0

    setState(() {
      _totalAmount = principal + interest;
      _dailyDueAmount = _totalAmount / (days > 0 ? days : 1);
    });
  }

  void _submit() {
    if (_formKey.currentState!.validate()) {
      final loan = LoanEntity(
        id: widget.loan?.id ?? '', // Will be generated by DB if empty
        customerId: widget.customer.id,
        principalAmount: double.parse(_principalController.text),
        interestAmount: double.parse(_interestController.text),
        totalAmount: _totalAmount,
        dailyDueAmount: _dailyDueAmount,
        outstandingBalance: widget.loan != null 
            ? (double.tryParse(_outstandingBalanceController.text) ?? _totalAmount) 
            : _totalAmount,
        startDate: widget.loan?.startDate ?? DateTime.now(),
        endDate: (widget.loan?.startDate ?? DateTime.now()).add(Duration(days: int.parse(_daysController.text))),
        status: widget.loan?.status ?? 'Active',
      );

      if (widget.loan == null) {
        context.read<LoansBloc>().add(AddLoanSubmitted(loan));
      } else {
        context.read<LoansBloc>().add(UpdateLoanSubmitted(loan));
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    return ValueListenableBuilder<String>(
      valueListenable: AppLocalization.languageNotifier,
      builder: (context, language, child) {
        return Scaffold(
          appBar: AppBar(
            title: Text(widget.loan == null ? '${'Assign Loan to'.tr()} ${widget.customer.name}' : '${'Edit Loan for'.tr()} ${widget.customer.name}'),
          ),
          body: BlocConsumer<LoansBloc, LoansState>(
            listener: (context, state) {
              if (state is LoansLoaded) {
                ScaffoldMessenger.of(context).showSnackBar(
                  SnackBar(content: Text('Loan assigned successfully!'.tr(), style: const TextStyle(color: Colors.white)), backgroundColor: Colors.green),
                );
                context.pop(true); // Return true to trigger reload
              } else if (state is LoansError) {
                ScaffoldMessenger.of(context).showSnackBar(
                  SnackBar(content: Text(state.message, style: const TextStyle(color: Colors.white)), backgroundColor: Colors.red),
                );
              }
            },
            builder: (context, state) {
              final isLoading = state is LoansLoading;
    
              return Padding(
                padding: const EdgeInsets.all(16.0),
                child: Form(
                  key: _formKey,
                  child: ListView(
                    children: [
                      TextFormField(
                        controller: _principalController,
                        decoration: InputDecoration(
                          labelText: 'Principal Amount (₹)'.tr(),
                          border: const OutlineInputBorder(),
                        ),
                        keyboardType: TextInputType.number,
                        validator: (v) => (v == null || v.isEmpty) ? 'Required'.tr() : null,
                      ),
                      const SizedBox(height: 16),
                      TextFormField(
                        controller: _interestController,
                        decoration: InputDecoration(
                          labelText: 'Interest Amount (₹)'.tr(),
                          border: const OutlineInputBorder(),
                        ),
                        keyboardType: TextInputType.number,
                        validator: (v) => (v == null || v.isEmpty) ? 'Required'.tr() : null,
                      ),
                      const SizedBox(height: 16),
                      TextFormField(
                        controller: _daysController,
                        decoration: InputDecoration(
                          labelText: 'Number of Days'.tr(),
                          border: const OutlineInputBorder(),
                        ),
                        keyboardType: TextInputType.number,
                        validator: (v) => (v == null || v.isEmpty) ? 'Required'.tr() : null,
                      ),
                      if (widget.loan != null) ...[
                        const SizedBox(height: 16),
                        TextFormField(
                          controller: _outstandingBalanceController,
                          decoration: InputDecoration(
                            labelText: 'Outstanding Balance (₹)'.tr(),
                            border: const OutlineInputBorder(),
                          ),
                          keyboardType: TextInputType.number,
                        ),
                      ],
                      const SizedBox(height: 24),
                      
                      // Math Preview Card
                      Card(
                        color: Theme.of(context).colorScheme.primaryContainer,
                        elevation: 0,
                        shape: RoundedRectangleBorder(
                          borderRadius: BorderRadius.circular(12),
                          side: BorderSide(color: Theme.of(context).colorScheme.primary.withOpacity(0.2)),
                        ),
                        child: Padding(
                          padding: const EdgeInsets.all(16.0),
                          child: Column(
                            crossAxisAlignment: CrossAxisAlignment.start,
                            children: [
                              Text(
                                'Loan Summary'.tr(),
                                style: TextStyle(
                                  fontWeight: FontWeight.bold,
                                  color: Theme.of(context).colorScheme.primary,
                                ),
                              ),
                              const SizedBox(height: 16),
                              Row(
                                mainAxisAlignment: MainAxisAlignment.spaceBetween,
                                children: [
                                  Text(
                                    'Total Amount:'.tr(),
                                    style: TextStyle(color: Theme.of(context).colorScheme.onPrimaryContainer),
                                  ),
                                  Text(
                                    '₹${_totalAmount.toStringAsFixed(0)}',
                                    style: TextStyle(
                                      fontWeight: FontWeight.bold,
                                      fontSize: 18,
                                      color: Theme.of(context).colorScheme.onPrimaryContainer,
                                    ),
                                  ),
                                ],
                              ),
                              const SizedBox(height: 8),
                              Row(
                                mainAxisAlignment: MainAxisAlignment.spaceBetween,
                                children: [
                                  Text(
                                    'Daily Due Amount:'.tr(),
                                    style: TextStyle(color: Theme.of(context).colorScheme.onPrimaryContainer),
                                  ),
                                  Text(
                                    '₹${_dailyDueAmount.toStringAsFixed(0)}',
                                    style: TextStyle(
                                      fontWeight: FontWeight.bold,
                                      fontSize: 18,
                                      color: Theme.of(context).colorScheme.onPrimaryContainer,
                                    ),
                                  ),
                                ],
                              ),
                            ],
                          ),
                        ),
                      ),
    
                      const SizedBox(height: 32),
                      SizedBox(
                        height: 50,
                        child: ElevatedButton(
                          onPressed: isLoading ? null : _submit,
                          child: isLoading
                              ? const CircularProgressIndicator(color: Colors.white)
                              : Text(widget.loan == null ? 'ASSIGN LOAN'.tr() : 'UPDATE LOAN'.tr()),
                        ),
                      ),
                      if (widget.loan != null) ...[
                        const SizedBox(height: 16),
                        SizedBox(
                          height: 50,
                          child: ElevatedButton(
                            style: ElevatedButton.styleFrom(backgroundColor: Colors.red),
                            onPressed: () {
                              context.read<LoansBloc>().add(DeleteLoanSubmitted(widget.loan!.id));
                            },
                            child: Text('DELETE LOAN'.tr(), style: const TextStyle(color: Colors.white)),
                          ),
                        ),
                      ],
                    ],
                  ),
                ),
              );
            },
          ),
        );
      },
    );
  }
}
