import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:go_router/go_router.dart';

import '../../../../core/di/injection_container.dart';
import '../../../customers/domain/entities/customer_entity.dart';
import '../../domain/entities/loan_entity.dart';
import '../bloc/loans_bloc.dart';
import '../bloc/loans_event.dart';
import '../bloc/loans_state.dart';

class AddLoanPage extends StatelessWidget {
  final CustomerEntity customer;

  const AddLoanPage({super.key, required this.customer});

  @override
  Widget build(BuildContext context) {
    return BlocProvider(
      create: (_) => sl<LoansBloc>(),
      child: _AddLoanForm(customer: customer),
    );
  }
}

class _AddLoanForm extends StatefulWidget {
  final CustomerEntity customer;

  const _AddLoanForm({required this.customer});

  @override
  State<_AddLoanForm> createState() => _AddLoanFormState();
}

class _AddLoanFormState extends State<_AddLoanForm> {
  final _formKey = GlobalKey<FormState>();

  final _principalController = TextEditingController();
  final _interestController = TextEditingController();
  final _daysController = TextEditingController(text: '100'); // Default to 100 days

  double _totalAmount = 0.0;
  double _dailyDueAmount = 0.0;

  @override
  void initState() {
    super.initState();
    _principalController.addListener(_calculateMath);
    _interestController.addListener(_calculateMath);
    _daysController.addListener(_calculateMath);
  }

  @override
  void dispose() {
    _principalController.dispose();
    _interestController.dispose();
    _daysController.dispose();
    super.dispose();
  }

  void _calculateMath() {
    final principal = double.tryParse(_principalController.text) ?? 0.0;
    final interest = double.tryParse(_interestController.text) ?? 0.0;
    final days = double.tryParse(_daysController.text) ?? 1.0; // Avoid divide by 0

    setState(() {
      _totalAmount = principal + interest;
      _dailyDueAmount = _totalAmount / (days > 0 ? days : 1);
    });
  }

  void _submit() {
    if (_formKey.currentState!.validate()) {
      final loan = LoanEntity(
        id: '', // Will be generated by DB
        customerId: widget.customer.id,
        principalAmount: double.parse(_principalController.text),
        interestAmount: double.parse(_interestController.text),
        totalAmount: _totalAmount,
        dailyDueAmount: _dailyDueAmount,
        outstandingBalance: _totalAmount, // Initially balance = total
        startDate: DateTime.now(),
        endDate: DateTime.now().add(Duration(days: int.parse(_daysController.text))),
        status: 'Active',
      );

      context.read<LoansBloc>().add(AddLoanSubmitted(loan));
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Assign Loan to \${widget.customer.name}'),
      ),
      body: BlocConsumer<LoansBloc, LoansState>(
        listener: (context, state) {
          if (state is LoansLoaded) {
            ScaffoldMessenger.of(context).showSnackBar(
              const SnackBar(content: Text('Loan assigned successfully!', style: TextStyle(color: Colors.white)), backgroundColor: Colors.green),
            );
            context.pop(true); // Return true to trigger reload
          } else if (state is LoansError) {
            ScaffoldMessenger.of(context).showSnackBar(
              SnackBar(content: Text(state.message, style: const TextStyle(color: Colors.white)), backgroundColor: Colors.red),
            );
          }
        },
        builder: (context, state) {
          final isLoading = state is LoansLoading;

          return Padding(
            padding: const EdgeInsets.all(16.0),
            child: Form(
              key: _formKey,
              child: ListView(
                children: [
                  TextFormField(
                    controller: _principalController,
                    decoration: const InputDecoration(
                      labelText: 'Principal Amount (₹)',
                      border: OutlineInputBorder(),
                    ),
                    keyboardType: TextInputType.number,
                    validator: (v) => (v == null || v.isEmpty) ? 'Required' : null,
                  ),
                  const SizedBox(height: 16),
                  TextFormField(
                    controller: _interestController,
                    decoration: const InputDecoration(
                      labelText: 'Interest Amount (₹)',
                      border: OutlineInputBorder(),
                    ),
                    keyboardType: TextInputType.number,
                    validator: (v) => (v == null || v.isEmpty) ? 'Required' : null,
                  ),
                  const SizedBox(height: 16),
                  TextFormField(
                    controller: _daysController,
                    decoration: const InputDecoration(
                      labelText: 'Duration (Days)',
                      border: OutlineInputBorder(),
                    ),
                    keyboardType: TextInputType.number,
                    validator: (v) => (v == null || v.isEmpty) ? 'Required' : null,
                  ),
                  const SizedBox(height: 32),
                  
                  // Math Preview Card
                  Card(
                    color: Colors.blue.shade50,
                    elevation: 0,
                    shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12), side: BorderSide(color: Colors.blue.shade200)),
                    child: Padding(
                      padding: const EdgeInsets.all(16.0),
                      child: Column(
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: [
                          const Text('Loan Summary', style: TextStyle(fontWeight: FontWeight.bold, color: Colors.blue)),
                          const SizedBox(height: 16),
                          Row(
                            mainAxisAlignment: MainAxisAlignment.spaceBetween,
                            children: [
                              const Text('Total Amount:'),
                              Text('₹\${_totalAmount.toStringAsFixed(0)}', style: const TextStyle(fontWeight: FontWeight.bold, fontSize: 18)),
                            ],
                          ),
                          const SizedBox(height: 8),
                          Row(
                            mainAxisAlignment: MainAxisAlignment.spaceBetween,
                            children: [
                              const Text('Daily Due Amount:'),
                              Text('₹\${_dailyDueAmount.toStringAsFixed(0)}', style: const TextStyle(fontWeight: FontWeight.bold, fontSize: 18)),
                            ],
                          ),
                        ],
                      ),
                    ),
                  ),

                  const SizedBox(height: 32),
                  SizedBox(
                    height: 50,
                    child: ElevatedButton(
                      onPressed: isLoading ? null : _submit,
                      child: isLoading
                          ? const CircularProgressIndicator(color: Colors.white)
                          : const Text('ASSIGN LOAN'),
                    ),
                  ),
                ],
              ),
            ),
          );
        },
      ),
    );
  }
}
